apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-data
  namespace: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
