apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinepods

resources:
  - namespace.yml
  - volumes.yml
  - configmap.yml
  - httproute.yml
  - service.yml
  - deployment.yml
