apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinepods-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pinepods
  hostPath:
    path: /var/data/pinepods
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinepods-data
  namespace: pinepods
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: pinepods
  volumeName: pinepods-data
