---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgApsv2hfEoKg+YoxImQ4dZzwI4a3UhwRk94HA6mXoCOtnpkIzn4J4+MFklCH6my5qb7cHQhC9wimIVnIH4GFd9q6SBkOm4bhzrXNcmFPTWIDWSd99nYmclwroVuhrwG2PJLh372IimwdRNyyRcllGZbht/UPk4upLDf6PRz1Wlnc1c26BqyBVjC+sgGG6ba8hf04EXWoMZiZvaS5M9kGOsR1jbF2zQrxPKbo1yKRHvlGcWAOmY4xKt+205VKIQPwERSgQn8TlMs0zpZRA6ap3mHCfdpiGIrWxl7klOiD1r/Mm44Q/x77ch9bBQd4MKO/8LfcvcTxgp/IoG1Q4XtQQ/AG8IA5QAtu2BAdsNjHmiyAORhHI6CsNPVwxAWGJY/5L296bNxCcESdwyhVp+gCHc9q+ds5lzshjVOMjXkBnD/zY7GH4Bqsh4++FowO6UBGdiytzjbC+0RUatZa299MQddQ87QksHAOVT9RJpqpeB6RIRWyt+vuJmxbgmmtzyOuKH7RrJJg2gbLdcFjVZxtzh4QvSXi1DM+8KLJ+VI1pyBYZfFBvZLLOk7HFDEyyUJsUFvgRQ2/afTBXXIAYd1Y5I/myhXRSVuF4bTA5NcGjEsPhD5PMvuSKJokvq0hXTep+vwUlDAM63EtnVERB9GSAWk6aHXmZDQokEWHk8LSXD6xLXC7Kvcd4VzF1NFqxrS1H00nFLwp+71Kc1z9z7QLSlOg1xOag==
    ACCESS_SECRET_KEY: AgADdJYOAqfeZAXoUGtAcANeF/YlYAhAUCbhB2B4/yqhQf2NH6C/cLyZaHi9uevPP8x5XN6ewO10oe1tqpWxFzukrOskKFuDjh/Wo0V4ln7WYDhokSihYMQrogsjHYu7orRnh/F7Dj/92CUXh51hbt56lHpf4+gngPWX5akXK2ITuJNpUtLA/BdzrdoKgUHR+QRcMypfIEgJg3TFPRi0bxWl2tZ6/zkQvP5eJq0iqtFC/7OfoPctURJWj22aLbblNnoYysvoxZiZ39sSgRqacqnf+I7QhtIMmvAh5XYEM0hrCKRaDQ5GIfRKk+T+29EHNyfHtHY6H1/EU42dOt2uCf1pWZXoQ8oeKRxHvsWNq+fJH8wfpUKbMMkJJ4crF8Mah142GY210CE5If1i/BuMdtla3THUp4rAolr4rWuZvAc/uipvm7FXkOlwBn2pbmPt5dUQbMklbmtyaX88Q5ZrubrqkGNeYpJldq643SYG7Glf/cQlLKL2lc8hwZJIKz6wJdbeE8kh6pXdVNHFe57r99tXlI1n7MoUYVFosGmo8lKh1R8scNHifClT7RJ0K+6i4kbjfcnac0ZTlIkFmAewOAqVWbzdZ0JHE35n4uYrz1aK+X647NwlK71WlAh6yDS2EfoIzfZJOrHP6rfk+cl6Yx2B7XrU6iIDev5yWtZt1YHWlTUS9TSc7PQdVN32/xUUhfGU1SsIBhy2S+s9CPO2LlGgz7k8FvGCZSQRD+qv095aqMLlVrPLtP43
  template:
    metadata:
      creationTimestamp: null
      name: aws
      namespace: nextcloud
