---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBkzZQ8Q6rdkDSDkz3pLT2sGp1dBGWszUd+rBFjTxgv5nD+duIEz6BnWVdna3v/DB4o+/QzsWqPiwy5XyXUASjNbZNeVTS+yFqbaTXuio8rKU+p9C5rtB9pk1dItLhrH15fXkdCcVWGVkFAcbmHHIBr+7YSqJrqKZCHbEKCZAbqpd18w5iULL5VFbMQ/60eELoFJwerna9vGoF+uzVPhXqyHgJ11UE7dZpHFPpdV89CF48h+3ez9MEE0tw4PyGX4mIP0H9/KODSd5ifottpOG2KUkZDf2TasKev9+6g0gIUIYdD4WleDP2TUQRHgqrs4dY3edSJun0yOOWePETixF7c9NWURl6wEuWJQwtWxtM7Sotw2CDcmJgAmP2zV/8lUnAr8aj3DTYxCnpyRLT/6XXC1dlH9+lWZ2/3wNWw0oQ+eTRGQMNWVQfNVfwwXX4BiSxF2Ge+jV4mDtU/ypL+3rJ6/E6A1/CNN3qxfmSYw0eaT6FkfXyaLpTkvTNJvmxzka5/mcLdUGfnVvqP7FUwKsvRzs8xVwZ7UStg5c6F6Ks0QcOkqAunsK7q5a/52SPGhDHl1MT6PkNYOyjwaFO0dNXZNlfTY9OmBAiAnaFU3KMgtNf2ufMAnzznFygYnAoknCgi8nqrwSWe+Ez7+TgRnByX3mcAGNBFhkPNsevYFSB7NPEx4Dkm+DMfAbbbOatuqOYbzSa8cIeY8CgPjMW0fH/of/Fzsw==
    ACCESS_SECRET_KEY: AgCYTofJMWTSremfbikV9EN2YX9/WqJUUewNHNoCYBher+cx3Am8KROJPzK0efJ5+riRJdnhHW5nHVREwVe7UlOgdJRFtPjl5og7EFohWYC4dLszD/OQELnc/CUFLrFfsWjRrh4KHTLirvlvkWQQwjghN9yC2/oPoZP+iq4C3TAAkjkKkP53CiV67uQgsaizluEaPrjwSsmJWVL/66ZBKlooNGdQtQt95dHKWXgV8Dq3pZMmNVLIdC3ON7FYYrtTQjL8UP3ENp4/GvJf/c3+zXzaJn1bCAfa6b1jRdKZfRmyZEs9CiZVm8WbEQUI0BD/E/x6LtcZRuB1G01ePuBGBaRHqujwsikK6DiOlkmr1fAKhoTLR8NMky3l5/Ie2Vsmx1MRB4dBXqQhxuXXNfNJsZGEkF1yg3YY+0nooSN674fJgPEvYep80mdl/XTnHxBXGfWa22wGiYk40MA4y2KQdQ0II6AOEzMxdDo8HO1hwWzswUOr8KZWXbZnkf7FtzO04B2PxOOX4Z4E98/M5sRUIeagvb2+uamT0EcI0l2409zfOX548oM7GLiP83nFE21pjcMacJVn+U5Ps6P46HYbLJkXPUzgMW5YdFHHDfWuplgcfqAIsq48fqEvBrIdgFyk9pZ0/ZK4bOO/xwcsVEx8i85jzdRFMisW02N/6g8a0+ysQbwd5cRoMv+De81JWQSAZ32n4By7nxQTs5JHbS7gX0oBqUqzXtMj69FV/6NAluGdMq0W4Y7jf1M
  template:
    metadata:
      creationTimestamp: null
      name: aws
      namespace: nextcloud
