---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCayoPH6SFvVWOqbhVp3XO8Twth57GK+g4vIlY9PdiWeFXhsOhuzut4l9ErIB/wArNNQa4BgMJIPbM1tDMfJ07o/FnzblX2VTKmW1VOILWQrVHaBwcMqrUGFjJ1AAEIsh1Dse02qv/qtcUgn+L5+2sX4ZXHbiU/H6Ys7aRc10LSV2UYE82C1IIMPDXqheX93z83HAUfeuAr+1rOJKXOlB+ONnQmaJICWncqj+Mi1i5p1m3BOE1J4J1Zs1+sZiBYdxKL9GwMZe2Yg5zEmTsAycCWP4pT1Jut6lFRKaIYSg0Lfzi1IuGwboMT/rN74eiIeTq01dsBVkikN0NHqFmqzrEBvEj3oPmhdlXZQVpbBxKD/0tx4AOX7R+zoc963fOKhOOLj5WhdFnUfWG7juqoOwiicq470rT61iexavbxwR9K2xtZZswejPF/NmabcFFmtbr0V+gutp6XtndILvB0D4QNYDZ9w4fWQtSXf36AqpDHVJ7Mz21qO5SMmIiDDETbPhdo314zITvojfTjMbmdJP2mxV1TU4ojPTkXeDmf8tegK1nI4gWipYDzmEZOS583a07xUlDhJSgLZTfPZlw/l5eynKi5RwrNlLViEzcX7EAhbO3Nalf1gvWveb/yBbOaaFD/K7pB7ihDuhL8HWMInaxCcGFJ7Q3OJq9GyNCwEzNnBqSQ6ATFgkB9IqoKMqPZTnNuJRhFJAewt3HY5DlDwrcWixpbloaUw8S8S/R+ArqF8rHatC60GCT0SuhwFiktKzIU02Lj37gMPa+PKwzudUv6ChvdFt4ZHPAY/7yVrf9aIdh1dtYdrIAIueAUQYkzzBqpaVIBkTimNhzMmmgiJ9YrrkKsNFfJE8VUYHL7HqqwVbG4iSlVo8RZ7Cotm8np09NItp3idc/xhVVaOdG2fz6QEPuUA713gylaSUxi
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
