apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookorbit-library
  namespace: bookorbit
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bookorbit
  hostPath:
    path: /var/data/books/library/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookorbit-data
  namespace: bookorbit
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bookorbit
  hostPath:
    path: /var/data/books/bookorbit/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookorbit-library
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: bookorbit
  volumeName: bookorbit-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookorbit-data
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: bookorbit
  volumeName: bookorbit-data
