apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:0.24.6
          ports:
            - containerPort: 3456
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: "https://vikunja.leotsgo.dev"
            - name: VIKUNJA_DATABASE_HOST
              value: "vikunja-cluster-rw.vikunja.svc.cluster.local"
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-db-secret
                  key: password
            - name: VIKUNJA_DATABASE_TYPE
              value: "postgres"
            - name: VIKUNJA_DATABASE_USER
              value: "vikunja"
            - name: VIKUNJA_DATABASE_DATABASE
              value: "vikunja"
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: jwt-secret
            - name: VIKUNJA_REDIS_ENABLED
              value: "true"
            - name: VIKUNJA_REDIS_HOST
              value: "vikunja-redis.vikunja.svc.cluster.local:6379"
            - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
              value: "false"
            - name: VIKUNJA_SERVICE_TIMEZONE
              value: "America/Sao_Paulo"
          volumeMounts:
            - name: vikunja-files
              mountPath: /app/vikunja/files
      volumes:
        - name: vikunja-files
          persistentVolumeClaim:
            claimName: vikunja-files
