apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-files
  namespace: vikunja
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: vikunja
  hostPath:
    path: /var/data/vikunja/files/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-redis-data
  namespace: vikunja
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: vikunja
  hostPath:
    path: /var/data/vikunja/redis/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: vikunja
  volumeName: vikunja-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-redis-data
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vikunja
  volumeName: vikunja-redis-data 