apiVersion: v1
kind: PersistentVolume
metadata:
  name: beaverhabits-data
  namespace: beaverhabits
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: beaverhabits
  hostPath:
    path: /var/data/beaverhabits/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beaverhabits-data
  namespace: beaverhabits
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: beaverhabits
  volumeName: beaverhabits-data
