---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws
  namespace: wallabag
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAbJAuMFXGqX1vrwEXStTITd/NoixoygMbnPogkKFZF4b9qNaiW0FUveiZjZvh1J31+1eyrxuhUs7YoCtf/99jGURC+EMcqTbW662+03OZTrEBjt8bTXORXBdnLjUVZiZbMatJ5wdsgp2/IRbmRBWacllyX5vaByKdRxvNej1NtL1/d96lEmSr0XHeJrGUxqA8NohJsFgUzO8oBNcju/MnXfrkOkL+asT3bthYbXaIgjIF08GZCZxCPz4qQr0KSKfj6/RiF6PdEqb6kAFqVgwuOSN4dQgXx+LI0XOJBeGL6ibFfZIQ7xMNXhATJ9CgDABkEyPqJjG/HgMqhUCC3B1k0W0XGlB4j9GQU5KWiNrq7b1MZ04V+AfSTq7ip5A+PUrQ7N6boziwB0OoU/nQI/x6g4BtWBoNrP4QwQfo55yHDNroj6WKOVMc9xBD/ISyyq/fiLhrbfn3JxVWKf9wH2gmNDEvdqRyRNzpgX3EHD/pnxr8SNYNeEZbTo0kuvI7ql5r77N9KuNbACT3/d906T2niFJSB4V1GCe28EwlS1QL6tvUczCYkxZA9Q1CaHa0JhIk03Jn2XLWaMsTocTV7TBnppzolJb8owmpgv2J3TO86ggzg3FCjsxMrGD/MR/NMwhjlNOF8b6rzZg4LM2ydh5Z10UezdbJp7/1J3MmFUoFtcCC0FAiVY7Vttpv31PcN8++g+K3LHcDHIp4Y2f2+Sg/Qb70o+g==
    ACCESS_SECRET_KEY: AgBBaluIJP3+WLwnGm0O/AG5i/DCxk/3f2F8wJLoc2W86mFJ5JeFRrjbiYLm06s7jQ4TfujyTMsc5Ie1ZePAo5KeiKwZkGDUeW+agaxGe/4Tykt2jQoTb6JL9lCZrzDSjluIbOxyYhhePknqBTKX7Lpnklfc5OsUlASbYM2hXn1WZwuzYr5K2AsmtcUXoAvhdPBtn6EvKozDwDIxwuKFaCkfGK+GKG9ALVGJALqEq3kMoVDHOExvx7qjXBrtxfrsJZXbrgzpG49EcXLoknySM1jD4u01YZS8ZpS9z3z4wIVRfPPmuvurtE6lXz8ok+yE2Kkvc7Yyq7+QOpSABGvjqaVc/Gv7oFCnT4mKu/H/m1PWsK6jAx3/5YsfJ70CLehwYvsCxXuKHiIkAlwRMFfNyRP0nVxg1RlhH7zp+s+nSmZLpeICF2WZYwV7wcoTShmXmSfj6U42Ez7Wdzrg5Zq5Fv9JW0khVp1IlFKmvuMlhCqA5bwFlvAmIHypuwqu4TDqZrAfHOK91jfIdR9V+36pCSiR5HeZtABJL8b+w1dkShxtKK5e2nU8Zy8DIvZaQrQP+C7gJFLHTdMrbVNNN+O/XrpHWu+R6qOSHE+atGEXZ7K0CCexXiG0RtRR31TPTuocXOLvUY2MbTXyWFaihQlzUl8qUXxGgDE2bKBUiaSNL2V+D9ouL11tpjDASIY00CVmHKHoOiVhZs01Gkkv23UHE9Tsq7fdSocEq1gF9O0sm4IUT/qaLDPbjWsF
  template:
    metadata:
      creationTimestamp: null
      name: aws
      namespace: wallabag
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallabag-container-env
  namespace: wallabag
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAA38Dl56c6tf9sjBcK+2OsrIjvgwG5/hrCqGK5n3pAUmUbDIb2Qe9SO5x5Orxrx2w7ZOhTtJ0DwURtsEmtzIBjF4Do2K/LJDcL8LV/B3a8fDnWSoBu+5loNoAwnxNwmVfJZzBHctLlBWtdsqG8kUYImxKTpyJS5r6Y3ekKazWYZRdexS/YZwzWuPzVsrnwc1JElv4E0FWouNUSmVAfFLjJ9A2R8iP7jj7AIQ68OaqsELrqKIoRAyZslRQdoA2XOPpPUa9ibq8TrqWWrDzLc9qaavGRnR5zc38msDAyEV3u4bjWsx33IDpZlF/0Jn7cSS2zLrEQJK/OXPQVld+gXeJxXC++LDul/aoLAQhIXs1yTEG03048lfenqMEqMC298jb4Ti6EPM0MfB2HHXj7AByouQraKtUcOfzVEaxW8zmqTfX6oA+yZ4t1wT8E7tf6a3+9TE495Vtda8SblhRWUwCN0ALeii2htjH0iLKroVRta6EsD6+dNY8nRDWnSzpvkPf8vIV4tkqmjbqnlpq1IMMNjSqQBJiXCsWSvM1PJDoek7hdTx2E19STwCwmbwbdTfyMrBAp9KdP1zOq0AVKAeJ73+KnK2QbHfcOVF8xipbWaleliEwwAiZZCrBDnLrCjcz2/hRhiPTEvVin5Dc57W0cmXAVyDc9ep939t9i1oNxMO1FspJjQnTMD9uLBgRwgJDVcfV3d0J4wr/CcyC+88401gN/b/wDRjTN+PveCcr4CnunvwESv6Ao2DbjM5KSZaSkYoHaihDaJQml1C1MxZhT
    SYMFONY__ENV__DATABASE_PASSWORD: AgBwLmhiyNsAeePcGrCzHHHGgiAYMf6h2H0z5dYb9xqejO3UtouSr2JcVAbTezGP9LRrcidSNuDfKsePpSbWx4kKuxpxdLFzxeTpOwfhr6j2DWLkmV2gSOPzbN0eJ9W556Fg+ODOOkNMSF05Kfu+yK7z0UEjiS8DV8x11hte7khd7bCsZlRP+GMBN3dPB5Z2+Hw5obTgpBKvd+gu1MZRNcW/rSQyzTh/rjVnjeRh1IGJBkey+Olaz43cw/kKT57M7qD+G0px8XujEs53b008de9hRnlm9vxBLezxFqVkGGdelRha3wN8b6Xao5mjUOgYtq2zxoCHx43d1XuEXuYBliKvdz73fCMt8WYSoM//fFbzy0MQPEdILouAuwsrfffWL/tZskzWyTkqE2R6C8c3glADRcvx96CxJcxSO58WnPXGCcFnOiu+fMiuBtZa+bi+w464ss3pVIrzvphacijHV6sK8j/+RsqxkBxG6AJ3hmJUiycScTBHUD0oQqlqweg+Hy9OKn0CrKnu0EwaYWdcbi+fdvD62eUGwiCkL8ApYt0Hw5/rcLIK9xmTWnkMdlvCTWgZFC5GWzeOvwEnr1sSENj0lZ+6tmmHWF4drWnVBBzB8E8L5ShX24X1daqV8YG8u1hkHl7b0LILMUWA4jPPG5pAOqxRayIzb57UmzBpHcdWaHw0x487Qo1mmPZ6WFlNLcq3I03RLwLLhiGDBEqWr7qyOzmOX/mUl/6vq+E2/wCRMqf1YPp/eIt7TiMF0I9sf8hR7RV9iGILVogoj6NejRsw
  template:
    metadata:
      creationTimestamp: null
      name: wallabag-container-env
      namespace: wallabag
    type: Opaque
