apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: paperless-scheduled-backup
  namespace: paperless
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  backupOwnerReference: cluster
  cluster:
    name: paperless-cluster