apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-data
  namespace: couchdb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: couchdb
  hostPath:
    path: /var/data/couchdb/data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: couchdb
  volumeName: couchdb-data
