apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data
  namespace: sonarqube
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: sonarqube
  hostPath:
    path: /var/data/sonarqube/data/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions
  namespace: sonarqube
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: sonarqube
  hostPath:
    path: /var/data/sonarqube/extensions/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sonarqube
  volumeName: sonarqube-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: sonarqube
  volumeName: sonarqube-extensions
