apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "1.5.4"
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store-provider-azure
        namespace: kube-system
      interval: 12h
  values:
    secrets-store-csi-driver:
      syncSecret:
        enabled: true
