apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/databases
  - ../base/bookorbit
  - ../base/wallabag
  - ../base/paperless
  - ../base/nextcloud
  - ../base/couchdb
  - ../base/media
  - ../base/beaverhabits
  - ../base/yaft
