apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
  username: nextcloud
  password: nextcloud-db-2026
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-cluster
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 250m

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-secret

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
