apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-cluster
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path

  resources:
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 200m

  enableSuperuserAccess: true

  bootstrap:
    recovery:
      source: nextcloud-cluster
      database: nextcloud
      owner: nextcloud

  backup:
    barmanObjectStore:
      destinationPath: s3://leotsgo-data/nextcloud-db
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: b2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: b2
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"

  externalClusters:
    - name: nextcloud-cluster
      barmanObjectStore:
        destinationPath: s3://leotsgo-data/nextcloud-db
        endpointURL: https://s3.us-east-005.backblazeb2.com
        serverName: nextcloud-cluster
        s3Credentials:
          accessKeyId:
            name: b2
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: b2
            key: ACCESS_SECRET_KEY

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
