apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nextcloud
  hostPath:
    path: /var/data/nextcloud/data/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-data
  namespace: nextcloud
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nextcloud
  hostPath:
    path: /var/data/nextcloud/redis/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nextcloud
  volumeName: nextcloud-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nextcloud
  volumeName: nextcloud-redis-data
