apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books
  namespace: calibre
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: calibre
  hostPath:
    path: /var/data/calibre/books/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-config
  namespace: calibre
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: calibre
  hostPath:
    path: /var/data/calibre/config/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: calibre
  volumeName: calibre-books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: calibre
  volumeName: calibre-config
