apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-cluster
  namespace: paperless
spec:
  instances: 1
  storage:
    size: 1Gi

  resources:
    requests:
      memory: 128Mi
      cpu: 25m
    limits:
      memory: 512Mi
      cpu: 500m

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-secret

  backup:
    barmanObjectStore:
      destinationPath: s3://leotsgo/paperless
      s3Credentials:
        accessKeyId:
          name: aws
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"

  externalClusters:
    - name: paperless-cluster
      barmanObjectStore:
        destinationPath: s3://leotsgo/paperless
        serverName: paperless-cluster
        s3Credentials:
          accessKeyId:
            name: aws
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws
            key: ACCESS_SECRET_KEY

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
