apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-cluster
  namespace: paperless
spec:
  instances: 1
  storage:
    size: 1Gi

  resources:
    requests:
      memory: 128Mi
      cpu: 25m
    limits:
      memory: 512Mi
      cpu: 500m

  enableSuperuserAccess: true

  bootstrap:
    recovery:
      source: paperless-cluster
      database: paperless
      owner: paperless

  backup:
    barmanObjectStore:
      destinationPath: s3://leotsgo-data/paperless-db
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: b2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: b2
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"

  externalClusters:
    - name: paperless-cluster
      barmanObjectStore:
        destinationPath: s3://leotsgo-data/paperless-db
        endpointURL: https://s3.us-east-005.backblazeb2.com
        serverName: paperless-cluster
        s3Credentials:
          accessKeyId:
            name: b2
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: b2
            key: ACCESS_SECRET_KEY

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
