apiVersion: v1
kind: ConfigMap
metadata:
  name: beets-config
  namespace: media
data:
  config.yaml: |
    directory: /music/soulbeet
    library: /music/soulbeet/.beets_library.db
    import:
      copy: yes
      write: yes
      timid: no
    match:
      strong_rec_thresh: 0.10
      distance_weights:
        missing_tracks: 0.1
    fetchart:
      auto: yes
      cover_format: jpg
    embedart:
      auto: yes
    replaygain:
      auto: yes
      backend: ffmpeg
    chroma:
      auto: yes
    plugins: fetchart embedart replaygain chroma lyrics info
    paths:
      default: $albumartist/$album%aunique{}/$track $title
      singleton: Non-Album/$artist/$title
      comp: Compilations/$album%aunique{}/$track $title
