apiVersion: v1
kind: Service
metadata:
  name: ai-memory
  namespace: ai
  labels:
    app: ai-memory
spec:
  selector:
    app: ai-memory
  ports:
    - name: http
      port: 49374
      targetPort: 49374
