apiVersion: v1
kind: PersistentVolume
metadata:
  name: yana-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: yana
  hostPath:
    path: /var/data/yana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yana-data
  namespace: yana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: yana
  volumeName: yana-data
