---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: markmine-secrets
  namespace: markmine-dev
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgBPxmNOny32N9opVF6xNM9/sZHzQjodHEh5SyC+oFiCFcTKilp/qQgXdHTt7TFLR3QOIy/bPGjVgaot8+MH8fPSGDfwtcFIk+2C1pyHUUx7Gi90PI/B5O5MGa7VFQ+fZm8f3Grfo7LZGXsOgq6JMEqvFeK4qMfrgKmO+4QW5YIJNA5dzFDtouJ37toUmCOyZq08JK55NmzKnL5yABm2Rq11J3XML9jFSz/P7ZdoHYXRS2RA28r+EKxpyBM4XxeKyZTRTuaXqmET5C9i1Tuz6cOedaFzoQk6Lu8I/FmvHil0s3VDslf/K5FD2n003j3ai48YryKkh56ujE1MklxrWBvjcwsZHjf/bku6OwKDPb5LJutwnEWJT9ORjDS1D1J4CG82qYfGWnZ8djDarG4QZa5UotSTmDGS4z4PDVH3xb5R6WGHy17M+hwn9pMms77j8l89xOz5uoC/WbEua8kY2d90ELC0yjSrCs037IioiMnW6MFkyp4eJmocV2uGCNCogQNVyc9lJFLzFiVKo4zznxY2ShbEUO4+7u+j6Dmuqhser3yHdIR3ikNw17WNxxITwNQHTikmNKAyGC7izz7AVA07J7FkpdynPLKL9NfDADLJYJiQ/Lx5Hf9y+gW2M9Uw7n0rvNpXEdzE8SwoKj6qiObZjRNY8HWai1SpeOH/Jg7MDO29F94awjMAo75x4CIHDH1mTsjIZItGXhEMaf2dnKwylBSI9DR++WyAeOyCVefMvIIeuMcH+fuFeALYcg==
    DATABASE_URL: AgCPV0DsHBEVEv9iC2zNI4Rw2E7UehxXhxbYtz5etcB9mrvr9xAiLsJZ3YzoGGv7B/qwY2SwaMwJWwWQ9DNb+nByAtT/jdFBxKIwVgy3KJWXYTxa3WCsrV0qZTUOdLTQ9jKXj8cFyyKyrpoJ8bRN4ZjhQqB3gMBWyB/pY3jxbs4/OTVGoAjwMcAwgTh9ZsTYCF0vBuNexaWKH4H2mFaK/dpdAe2d8Kdlq4nES5Mz+Oh482DBCzc/RjVejKuNqPTNX3P1NKMPKJ0QzYrV6r35DUUahI02IQGu+iHG8MrDe3ITwozLBgkbe8PbxguGu+DVUI/jwv8/bMSa9YRWTRYHNQ3HBLCBpNixLnZ9CFmKWzWxSzn+AN/Db6n1oyxte7/a9W6QE7soxKyUCFZfEm3rEU6Vqto5LP2vtA05WqQNu9iSvuNNT5iBmUwrW6o9G3Dq7q74BRSNmJED+KG1FGHotiwGfbJRP7VOudE7AS5ylxpFIMgNAlLDl9b9nAIwC70mDd2MsAakX/8MNFAKsNWFmv0blFsc3LzrC0F4YHq97CV1tq8vt+m58gIwNzJWNWEoITS6S6fIs3jWPMmeiXTc1FeBJLZr1e1kBjCiXMTtqhJ7aQrT1FqK54cbHoArjN1t1+BGJh3VemyD/WAWGZ+tJpnCiECNp9ptQlMpUGjti7/l5/z5FKP7j04aMZCWwZQotlpnHBcqXqHJtxSuntRE1l6xNxrzeT9M++s9eqIdHxV6Gv5imdqyWokISdHwvACHZuhfuNBAKTgYyrQnRjHoZePxuosoBHKO9wTJF9em
  template:
    metadata:
      creationTimestamp: null
      name: markmine-secrets
      namespace: markmine-dev
