apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: markmine-db
  namespace: markmine
spec:
  instances: 1
  storage:
    size: 2Gi

  resources:
    requests:
      memory: 256Mi

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: markmine
      owner: markmine

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
