apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: databases
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.1.2
          args: ["--save", "", "--appendonly", "no"]
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: databases
spec:
  selector:
    app: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
