apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
  namespace: immich
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich
  hostPath:
    path: /var/data/immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-cache
  namespace: immich
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich
  hostPath:
    path: /var/data/immich-ml-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: immich
  volumeName: immich-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: immich
  volumeName: immich-ml-cache
